version: "3.9"
services:
  db:
    container_name: db
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    environment:
      SA_PASSWORD: p1fgVFQ2rtR97nt
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "p1fgVFQ2rtR97nt" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s